server:
  port: 8888
  servlet:
    context-path: /api/v1

spring:
  application:
    name: muasamcong


  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/muasamcong}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    org.hibernate.SQL: off
    org.hibernate.orm.jdbc.bind: off
    org.hibernate.orm.jdbc.warn: error

gateway:
  url: ${GATEWAY_URL:http://127.0.0.1:18080}
  key: ${GATEWAY_KEY:secret}

storage:
  root: ${STORAGE_ROOT:downloads}
